project:
  type: website

website:
  title: "Mynara-Archives"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.scss
    toc: true

execute:
  freeze: auto
