# Gods of Mynara

## Divine Origin

Many gods arose as their domain formed in the world. Unome, Elemental Confluence, for example, manifested from the confluence of the four elements in the material plane, Bolgrod The Annihilator existed before that in the emptiness before the elements. Some however emerge from the wants and needs of sentient creatures. Dylgrac the Weary was created after the first warriors were left behind alone and broken in the fields of battle, and Scios God of Craft and Mining was created as clerics of Unai, Origin of Life focused increasingly on craft and diverged from the rest of their sect whose focus was on cataloging and natural conservation. 

### Ascention

Mortals have ascended to divine status in their death by garnering an extraordinary following and dedicating themselves to a single pursuit that no god currently claims as their domain. These ascended mortals are notated in this text with a #Ascendant tag under their name. These Ascendant gods are by far the youngest and most frequently manifest their avatars to directly intervene, they also most frequently have narrow domains as they have not been changed over time by their followers needs.

## Alignment

The gods of this world are beyond traditional mortal questions of morality. While the gods do occasionally interfere in mortal endeavors, some more than others, or choose champions, their actions are not malevolent or benevolent they simply are. The deities are in part created through faith, and in part material, however they are responsible for their domains and act to tend their domain. Both good and evil individuals follow each god, so long as they act in line with that god's edicts and anathemas the god will shine down on them.

## Selecting a Deity

While clerics devote themselves to a single god, most mortals pray to gods depending on need. Some who's prayers are heard may choose to keep a shrine to a specific deity in their home, or wear their symbol in continuing gratitude for divine aid, but most keep simple shrines that are of general utility or utilize a community shrine. Few deities demand full devotion from their followers. When choosing a Deity for your player character it is important to consider the type of campaign you will be playing, the values of your character, and the values of the other members of your party. While not impossible it is unlikely that a worshiper of #Albrea and #Nolduro would willingly work together. To avoid continual inter party conflict, if you plan to devote your character to a specific deity be sure to communicate that to your party members.

# Albrea, Solar Ascendant

#Albrea 
#Ascendant 

## Domains

- Sun

## Edicts

- Destruction of Undeath in all forms
- Shine light into darkness

## Anathemas

- Artificial or magical darkness
- Undeath

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Athletics

### Favored weapon

Mace

### Cleric Spells

1st: Disrupting Weapons, 2nd: Fear the Sun, 3rd: Searing Light, 4th: Holy Cascade, 7th: Sunburst

## Notable history

After #Nolduro died and provided mortals with the gift of creating undead, hordes of creatures were risen to march upon cities and nations who could not defend from armies that needed no sleep, no food, no water and marched in perfect unison under a necromancer. This led to an era of lich kings tyrannically enslaving the living and harvesting corpses for their armies. Without a god's aid to oppose this power Albrea sought aid in nature. Drawing upon the sun's burning light Albrea dedicated herself to eradication of mindless undead in life and inspired a holy order of clerics to follow her into battle. Through her crusade she brought light across the world and brought balance back to the world of the living and undead.
Followers of Albrea tolerate the existence of sentient undead, and hold a tenuous respect for those risen through #Teneth , but will eradicate creatures risen by #Nolduro on sight.

# Ardensia, Soul of Civilization

#Ardensia
#Ascendant

## Domains

- Cities

## Edicts

- Build and expand cities
- Through Cities grow the influence of sapient creatures on the plane
- Strive to create a single city that consumes the plane
- The needs of the city must come before all other concerns

## Anathemas

- Uncontrolled Nature
- Stopping a city's growth in favor of conserving nature

## Devotee Benefits

### Divine Font

Harm or Heal

### Divine Skill

Choice of Craft

### Favored weapon

Light hammer and Light Pick

### Cleric Spells

1st: Mending, 2nd: Knock, 4th: Hallucinatory Terrain, 6th: Wall of force

## Notable history

It is widely debated if Ardensia qualifies as an ascendant deity. Arden's I was not a mortal, or even a creature at all. Once a vast city Ardensia spanned coast to coast on a larger island before an astral impact leveled most of the structures and caused great waves to wash away the city. A testament to what can be accomplished by the combined efforts of mortals and a well designed metropolis it is said that in their simultaneous deat the spirits of Adensians united in death and gave rise to the god of cities. Shortly after the fall of this great city mortals lurched forward in their colonization of the plane. Inspired by visions of a vast metropolis what were once small towns were spurred to expand. It is said that without Ardensia's influence the mortals of the material plane would be nothing more that warring tribes. Ardensia's clerics often find themselves as city planners, architects, and crafts folk dedicated to the growth and function of their city.

# Bolgrod The Annihilator

#Bolgrod

## Domains

Void
- Darkness
- Destruction
- Nature
- Fate

## Edicts

- Relinquish all worldly attachments
- Vow of poverty
- Obligation to ease the end of things that have outlasted their utility to nature and their community

## Anathemas

- Engage in purposeless necromancy or animation of objects
- Waste resources or participate in gluttony

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Nature

### Favored weapon

Sling

### Cleric Spells

1st: Sleep, 2nd: Invisibility, 6th: Disintegrate

## Notable history

Balgrod is one of the more passive deities, however many have used their name to promote many atrocities. It is a common misconception that balgrod seeks to hasten the end of all things, or endorses wanton destruction. Balgrod's sole concern is the peaceful transition from existence to non existence at the appropriate time. Many of Balgrods devotees claim visions of death and destruction, however they often vow not to reveal these visions for fear of disrupting their passing at the appropriate time.

# Dylgrac the Weary

#Dylgrac

## Domains

Recovery for those who have fought with honor
- Travel
- Family
- Luck

## Edicts

- protect those who have given all they have in their pursuits
- Ease the thoughts of those who have sacrificed
- Reunite those who have journeyed far with those that they fight for

## Anathemas

- Disrespect of the fallen
- A failure to sacrifice for you beliefs when challenged
- Abandonment of a comrade

## Devotee Benefits

### Divine Font

Heal

### Divine Skill

Survival

### Favored weapon

Spear

### Cleric Spells

1st: Soothe, Create Water, 2nd: Create Food, 5th: Dreaming Potential

## Notable history

A commonly venerated god by soldiers and the righteous, Dylgrac is a beacon of hope to those who have sacrificed for their beliefs. The followers of Dylgrac are beyond selfless and will journey through the hells if they have to in order to bring the weary back home. Dylgrac shields those who have fought bravely as they return home regardless of the side of the battle they fought on, it is not uncommon to see battlefield medics that venerate this god tending the wounds of hostile and allied fallen alike. It is due to this respect for the fallen that all but the most ruthless and callous leaders make it a grave crime to strike down a cleric bearing Dylgrac's mark, and their devotion often gains them passage through otherwise hostile lands.

# Gohoon, Conqueror of the Unworthy

#Gohoon
#Ascendant 

## Domains

Dethroning unworthy rulers
- Ambition
- Might
- Zeal

## Edicts

- Dethrone the unworthy
- Broaden your understanding of those you live amongst
- Seek out those who would best serve their people

## Anathemas

- Act in haste
- Assume superiority
- Aid those who would not aid themselves if able
- Promote Tyranny

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Society

### Favored weapon

Bastard Sword

### Cleric Spells

1st: Biting Words, 2nd: Shield Other, 4th: Outcast's Curse, 6th: Righteous Might

## Notable history
While few of Gohoon's followers ascend to leadership, many rulers claim Gohoon's favor. It is not uncommon for rulers to keep a court cleric of Gohoon to reinforce their authority, though it is equally common for rulers to reject Gohoon's authority and deem worshipers traitors and enemies of the state. It is because of this that worshipers of Gohoon often masquerade as clerics of other gods, or use their skills to rise through the ranks of government rooting out the unworthy as they progress towards their ultimate goals. Those who follow Gohoon make for devoted warriors and protectors of rulers who earn their trust and fierce opponents to those who are unfit to lead.

# Lizbet, Divine Hoarder

#Lizbet
## Domains

- Knowledge
- Change

## Edicts

- All crafted objects belong to Lizbet and mortals only borrow their possessions from them
- Sentimental connections to objects must be weighed equally against material need
- Knowledge of where an object came from and the hands that it has passed through is as important as the object itself

## Anathemas

- Willful ignorance of an object's true owner
- Claiming ownership over something without devoting appropriate consideration to its providence
- Stealing from those of greater need

## Devotee Benefits

### Divine Font

Heal

### Divine Skill

Society

### Favored weapon

Scourge

### Cleric Spells

1st: Item Facade, 3rd: Locate, 7th: Retrocognition

## Notable history

Lizbet is a strange deity, often depicted as a many armed creature with a small head and beady eyes seated in piles and piles of trinkets Lizbet represents that all to familiar urge to collect and catalogue objects for the sake of it. Lizbet's clerics maintain that all material goods belong to Lizbet and mortals simply borrow them from her. For that reason, Lizbet's clerics are best known for "reallocating" goods from those with means to those without with little regard for "ownership." In their eyes all have equal claim to craft goods, with a notable exception for those who created the goods, and by stealing and gifting items they are acting as a distribution network for items. In addition to their common perception as thieves and nuisances  they are also sought after for their unique skills in identifying the providence of items. They are knowledgeable in not only the origins of famous objects, but also are adept at seeking out the origins of objects. If you need to return something to someone, or identify if something is a forgery there is no better person to seek out than a cleric of Lizbet.
Notably, the scourges that these clerics carry are the best identifier of those who devote themselves to Lizbet's ideals. Clerics of Lizbet craft their Scourge from various Knick knacks and baubles that they come across in their travels. Each end of the scourge has a unique story as to why the cleric attached it to their weapon, but that story may be as simple as "I like the way it looks!"

# Meedaya, Divine Drunkard

#Meedaya

## Domains

- Confidence
- Luck
- Indulgence

## Edicts

- Push your fortune as far as it will take you
- When given the opportunity, indulge yourself to to the furthest extent that you are able. 
- Have confidence in all things even in your knowledge of your own shortcomings

## Anathemas

- Do not act boorish in your indulgence
- Do not overestimate your position
- Do not allow your confidence to become greater than your fortune or ability

## Devotee Benefits

### Divine Font

Heal

### Divine Skill

Performance

### Favored weapon

Staff

### Cleric Spells

1st: Detect Poison, 2nd: Enhance Victuals, 6th: Feeblemind

## Notable history

Meedaya is quite literally the life of the party. Tracing it's origination back to the first celebration Meedaya guided the hand of the first brewers, inspired the discovery of fireworks, and blesses banquet halls with protection and potent spirits. Providing her worshipers with visions of celebration she is the divine spark behind her cleric's feasts and parties. Encouraging her followers to rely on good fortune, kindness, and their own abilities she rewards their devotion in kind.

# Nolduro, Corpse Crafter

#Nolduro
#Ascendant 

## Domains

- Undeath
- Creation

## Edicts

- No creature is better dead than alive
- Then living have an obligation to use all tools at their disposal, and that includes the corpses of the fallen
- While creation of new life is the domain of #Unai sculpting the corpses of Unai's passed creations is the obligation of disciples of Nolduro.

## Anathemas

- Burials are the ultimate waste of your earthly body
- Being buried with your possessions or in a container that impedes the decay and use of your body is greedy and selfish

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Occultism

### Favored weapon

Dagger

### Cleric Spells

1st: Unseen Servant, 2nd: Ghoulish Craving, 3rd: Bind Undead, 4th: Talking Corpse

## Notable history

In contrast with #Teneth Nolduro is solely interested sculpting new servitor beings from the corpses of the fallen. By carving and stitching them together Nolduro empowers his disciples with the power of gods. Creation of novel creatures from the raw materials of deceased creatures is an art reserved for mortals. Not only do these disciples create servitor beings they also augment their own bodies with undead prosthetics. Nolduro restricts the creation of undead to mortals and inhibits non mortal creatures from creating undead creatures. Before his ascension Nolduro was the first mortal on the material plane to master necromancy through study and practice without divine intervention. By perfecting this craft and focus on creation for creation's sake upon his death his power spread throughout the plane seeding mortals forever with the latent ability to create undeath.

# Ozoth The Devourer

#Ozoth
## Domains

- Indulgence
- Tyranny
- Ambition

## Edicts

- Consume all that you are able
- The world exists for those powerful enough to take it
- It is not enough to consume flesh and blood but you must consume their will and spirit
- If you would stand to gain nothing by consuming a creature it is sufficient to subjugate them

## Anathemas

- Selflessness is weakness
- Nothing must be saved for later, your appetite must be insatiable 

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Intimidation

### Favored weapon

Spiked Gauntlet

### Cleric Spells

1st: Command, 2nd: Enlarge, 3rd: Vampiric Touch, 5th: Crushing Despair, 6th: Vampiric Exsanguination

## Notable history

Ozoth was once the god of feast and gluttony, however it's hunger grew and so did its ambition. Ozoth often comes into conflict with the worshipers of other deities as it's goals are myopic, wasteful, and selfish to a fault. However, Ozoth often finds champions in places of great need. When an individual is pushed to the brink of death, when they are the sole survivor and are not out of the woods yet this is when Ozoth comes to them. Ozoth pushes people to do the unthinkable. You are starving and can only survive by eating the corpses of your already dead children, you are backed into a corner and the only way out is by ripping them apart and frightening the rest with you brutality, you are at the mercy of worshipers of Ozoth and only by matching them can you survive. However, once welcomed in Ozoth does not easily release you. Even once free of the circumstances that led you to welcome Ozoth into your heart Ozoth drives you to consume, to conquer, to dominate until there is nothing left.

# Polatar, Shroud of Deception

#Polatar

## Domains

- Darkness
- Secrecy
- Trickery
- Knowledge

## Edicts

- Conceal information that could be used to harm others
- Use information to your advantage
- Share information with those you can trust
- Embrace trickery and evasion over force and brawn

## Anathemas

- Solving problems with brute force
- Providing information without personal gain
- Acting on unreliable information

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Deception 

### Favored weapon

Chakram

### Cleric Spells

1st: Charm, 4th: Discern Lies, 6th: Scrying

## Notable history

Polatar's chosen are those who excel in secrecy and concealment. This includes not only spies, but also smugglers. Polatar shields those who seek to conceal themselves and others from prying eyes.

# Poldaga, Combat Artisan

#Poldaga

## Domains

- Perfection
- Ambition

## Edicts

- Choose a combat style and perfect it
- Perfect your physical form for combat
- No combat challenge by a worthy opponent may be declined
- No combat challenge may be issued to an opponent from whom you would not deem worthy to accept a challenge from when death is a possible outcome

## Anathemas

- Fighting an opponent To humiliate them debases the challenger as much as it humiliates the challenged
- Using your skills to defeat the defenseless 
- Dying outside of combat
- Dying to an unworthy foe

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Athletics

### Favored weapon

Unarmed

### Cleric Spells

1st: Ant Haul, 4th: Mountain Resilience, 6th: True Seeing

## Notable history

Poldaga was created when the first monks perfected a martial art. Through their dedication to self perfection their collective belief created a new domain. Poldaga is often depicted as a many armed muscular humanoid wearing a long Stoll. Many martial artists and clerics of Poldaga don the impractical garment during training as they believe that if you master your movements and control your body you should be able to keep even the loosest garments in place as you battle. Some disciplines even incorporate loosely hung weapons and clothing into their combat styles creating what looks like a vortex of flailing weapons and fabric.

# Runai, Masochistic Revelation

#Runai

## Domains

- Pain
- Truth

## Edicts

- Through pain truth will be revealed
- Pain must be willingly received for the truth to be revealed
- Pain is not something to be avoided. All lessons are learned through pain.

## Anathemas

- Pain without purpose
- Pain delivered to the unwilling in search of the truth
- Self deception
- Torture

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Diplomacy

### Favored weapon

Scourge

### Cleric Spells

1st: Harm, 4th: Discern Lies, 6th: True Seeing

## Notable history

Unlike most deities who are created when their domain is first experienced or manifested Runai was created when the first coerced false admission of guilt was uttered. So repulsed by this abuse of pain Runai's followers seek to impose rule over pain and the existence of pure truth. These devotees often put themselves through brutal trials that test the limits of their endurance to strengthen their resolve if they ever face torture or coercion. Many individuals who commit themselves to the rule of law will partially commit themselves to the values of Runai, but only the most devoted will willingly subject themselves to pain.

# Scios God of Craft and Mining

#Scios

## Domains

- Earth
- Creation
- Ambition
- Indulgence 

## Edicts

- Create in both high quality and in high quantity
- A project can be fiNished without being perfect. Acknowledgement of flaws in your work is the first step to improvement and should not be dwelled upon.
- Devote yourself to honing your craft
- Assist others in their ambitions to hone their craft
- Create both for others as well as yourself

## Anathemas

- Disrespect of another's creation is a grave offence
- Creating poor quality goods in high quantity is a debasement
- Pursuit of perfection is only permissible as long as the benefits of perfection are not outweighed by the need for your craft

## Devotee Benefits

### Divine Font

Heal

### Divine Skill

Select craft

### Favored weapon

Light Pick

### Cleric Spells

1st: Summon Construct, 2nd: Shape Wood, 4th: Shape Stone

## Notable history

Followers of Scios are a talented and rambunctious bunch. Seldom placing much value on anything other than their craft and the pursuit of refining their skills they often strike others as self absorbed, this however couldn't be further from the truth. While yes, the pursuit of their craft is front and center they are equally as enthusiastic about helping others refine their craft and making their skills available to others. Scios disciples devote equal energy to celebration of craft as they do to the pursuit often holding great indulgent feasts, and parties to congratulate another craft person's triumph. Some find it odd that miners often devote themselves to Scios, Scios does hold domain over earth after all, but it is worth drawing attention to how much of what artisans use to create comes from the earth! Smiths use the ore that is pulled from the ground, chefs use the food grown from the dirt, painters use dyes made from ground minerals, and sculptors not only use clay, but many of their glazes are drawn from earth as well! Miners, while masters of their own craft, mining, are a critical part of a craft person's work and they command appropriate respect from any artisan who claims to hold themselves to Scios' ideals.

# Sodde, Wisdom Seeker

#Sodde

## Domains

Collect knowledge
- Knowledge
- Protection
- Truth

## Edicts

- Seek out and preserve knowledge of all types
- Document novel findings
- Verify the truth of information, but do not allow uncertainty to impede documentation

## Anathemas

- discriminate information based on your values
- Allow knowledge to be lost or forgotten
- Allow a proven falsehood to spread
- Allow your physical health to impact your mental well-being 

## Devotee Benefits

### Divine Font

Heal or harm

### Divine Skill

Society

### Favored weapon

Gauntlet

### Cleric Spells

1st: Mending, 4th: Discern Lies, 6th: Collective Transposition

## Notable history

Sodde is highly involved in the world through his devoted. You will frequently find shrines and other places of worship throughout places of learning, libraries, and museums. Many practitioners of law venerate Sodde and will use their blessings in pursuit of the truth. While Sodde abhors lies their devoted are encouraged to lie to those who would lie to others if it furthers the pursuit and conservation of knowledge.

# Teneth Chainbreaker

#Teneth

## Domains

- Undeath
- Freedom

## Edicts

- Waste nothing, not even the dead
- Undeath is the ultimate freedom. In Undeath you become free from hunger, sickness, age, and vanity. Humane assisted suicide should be offered to any who choose Undeath early
- No living creature should live in servitude and no creature in Undeath should be bound to a master
- The Spirit is equally as important to protect as the body
- Upon death you relinquish all rights to your physical belongings. In Undeath you may start anew

## Anathemas

- Total destruction of a corpse is desecration
- Binding a sentient creature, living or dead, to your will is the height of evil.
- Gluttony and waste has no place in the halls of Teneth

## Devotee Benefits

### Divine Font

Heal or Harm

### Divine Skill

Intimidation

### Favored weapon

Spiked Chain

### Cleric Spells

1st: Fear, 2nd: Peaceful Rest, 4th: Remove Curse, 7th: Mask of Terror

## Notable history

Teneth is a highly regarded deity among the oppressed representing the ultimate freedom. Priests of Teneth are often seen carrying the chains used to hold them in life that they have laden with spikes and blades to use their bindings to Punish those who would oppress others. These priest are liberators, and omens. To those who endeavor to subjugate the weak a priest holding a spiked chain may as well read like a death sentence. As such, slavers and oppressors keep a vigilant eye for Teneth worship and react swiftly and without question.

# Tolya of the Flowers

#Tolya
#Ascendant 

## Domains

Small creatures less than 5 pounds in weight
- Family
- Protection
- Nature
- Healing

## Edicts

- All life is sacred
- Vow to ease the early stages of life for all creatures
- Tend to native pollinator plants and insects

## Anathemas

- Harming small creatures
- Eating the flesh of a living creature
- Destruction of animal habitat
- Interfering with a pollinating insect

## Devotee Benefits

### Divine Font

Heal

### Divine Skill

Nature

### Favored weapon

Sickle

### Cleric Spells

1st: Ant Haul, 2nd: Speak with Animals, 4th: Breath of Life

## Notable History

Originally the god of flowers and pollination Tolya's domain gradually grew to include all small creatures and creatures in the early stages of life as their clerics took on these responsibilities for their communities.
Clerics of Tolya often act as midwives and vets for their community, but are not primarily responsible for these tasks as part of their beliefs.

# Ultheria, Leyline Guardian

#Ultheria

## Domains

Protect the sources of arcane magic at all costs
- Protection
- Magic
- Water
- Moon

## Edicts

- Clear any inhibitors to the flow of magic through the world's ley lines
- Construct markers at the nodes where ley lines cross
- Destroy anything that would interrupt the flow of magic through a ley line
- Prevent any one individual from overdrawing from the ley line network
- Destroy all sources of anti-magic
- Prevent the pollution or corruption of magical springs

## Anathemas

- Waste magical Energies
- Allow a ley monument to degrade
- Inhibit the natural flow of magic or otherwise attempt to redirect a ley line
- Pollute waterways

## Devotee Benefits

### Divine Font

Harm

### Divine Skill

Arcana

### Favored weapon

Trident

### Cleric Spells

1st: magic missile, 2nd: magic mouth, 3rd: levitate, 4th: blink, 5th: control water, 6th: wall of force, 7th: Ethereal Jaunt, 8th: maze, 9th: disjunction

## Notable history

Many believe Utheria to be one of few gods that venture into the material plane with regularity, though others insist that any physical representation of Utheria is only an avatar. Often depicted as a large sturdy amphibious dragon like creature with smooth translucent skin Utheria not only chooses champions but they also directly bring down their wrath on those that would degrade the presence of magic in the world. It is believed that the arcane forces ebbe with the tides and flow along ley lines like the rivers. While there are many types of magical springs, the most important to the devout are those that draw their power from ley nodes. These springs are one of few direct channels of magic from the ley network into the material plane. Where other springs may go stale as the source of their magic depletes so long as the ley network remains intact no "ley spring" will ever lose potency.

# Unai, Origin of Life

#Unai

## Domains

- Creation
- Nature
- Knowledge

## Edicts

- Conservation of the natural world and the cataloging of Unai's creations
- Document and share the discoveries of new species
- Maintain the natural ecosystem of the world
- Dedicate time to create and imagine the world in new ways as Unai does

## Anathemas

- Extinction of a species
- The allowance of a single species to grow uncontrolled
- The perversion of natural form with mechanical or other augmentation

## Devotee Benefits

### Divine Font

Heal or Harm

### Divine Skill

Nature

### Favored weapon

Sickle

### Cleric Spells

1st: Summon Plant or Fungus, 2nd: Speak with Animals, 4th: Speak with Plants, 6th: True Seeing

## Notable history

Unai was not created by #Unome but was the first thinking entity that arose after Unome brought order to the elemental chaos. Unai finding itself in a barren world of unforgiving stone, crushing waves, powerful gales, and destructive plane put itself to work elevating the elements into something more hospitable. First bringing about the building blocks of life in the ocean then gradually guiding these creatures into thinking beings worthy of keeping company Unai is thought as the originator of most life. While some creatures were brought about by other gods, Unai ultimately took responsibility for guiding these creatures in the world to find a place along side the other natural beasts and plants.

# Unome, Elemental Confluence

#Unome

## Domains

- Air
- Fire
- Water
- Earth

## Edicts

- Your face must be covered so as to hide your true intentions
- Elements are meant to commingle and be used in conjunction. Separating their usage into different domains is blasphemy
- The elements must not be considered separate domains, but rather parts of a whole

## Anathemas

- Use of an element to destroy innocents is a sin
- Fire must never be left to spread uncontrolled
- Water must not be allowed to flood unguided
- Earth may not fall without resistance
- Air may not be allowed to build momentum as a vortex to the point that it becomes destructive

## Devotee Benefits

### Divine Font

Heal or Harm

### Divine Skill

Nature

### Favored weapon

Sai

### Cleric Spells

1st: Choose one, (Air Bubble, Create Water, Burning Hands, Mending); 2nd: Summon Elemental, 3rd: Choose one, (Earthbind, Feet to Fins, Searing Light, Meld into Stone); 4th: Choose one, (Air Walk, Hydraulic Torrent, Fire Shield, Shape Stone); 5th, Elemental Form 

## Notable history

Unome arose from the chaotic elemental energies that confluences into the material plane. As old as the mountains, as vast in power as the writhing oceans, as quick as a cutting wind, and as fierce as a roaring fire Unome ordered the elements. Unomes four faces each watch over an element preventing it from overtaking the others. We're it not for Unome the material plane would have never formed from the wild elemental energies that ripped through space. Unome's followers value harmonious existence not only with the elements, but also with nature. Temples to Unome often feature carefully curated gardens that include features that showcase the four elements in beautiful arrangements.

# Zehlt, God of Heroic Aid

#Zhelt

## Domains

- Healing
- Zeal

## Edicts

- Provide Aid wherever required
- Eliminate those who would do harm swiftly and without remorse
- Harm reduction above all else

## Anathemas

- Harming an innocent
- Enabling someone who would harm an innocent
- Prolonging a painful life with no end of that pain in sight

## Devotee Benefits

### Divine Font

Heal

### Divine Skill

Medicine

### Favored weapon

Dagger

### Cleric Spells

1st: Spirit Link, 2nd: Remove Fear, 3rd: Neutralize Poison, 6th: Field of Life

## Notable history

Battle healers, Would be rescuers, those who have been harmed and continue to be in harm's way are all within the domain of Zehlt. Zehlt empowers their champions with divine might to provide help wherever needed; be it deep within the bowels of the earth, or high in the mountains Zhelt's clerics will find you to provide aid. Unlike #Dylgrac's disciples who focus on helping the wounded, Zhelt's healers carry medicine in one hand and a blade in the other. For Zhelt's chosen it is equally important to heal the wounds, but also punish those who opened them.
