---
title: The Empire
---
# The Empire

The Empire was a plane spanning governmental force that at its height led to great prosperity and arcanotech advancement. Today, splinter groups of the empire still exist and exert limited influence over nearby society, however their power is maintained through tradition and by relying on magical devices and weapons that they no longer understand. The secrets to maintaining their biodrives, wards, teleportation circles, and magical armament have been lost to all but the phantasm forest and the occasional eccentric who studies the old ways. It's not uncommon for cities to house a representative of the empire out of respect, but any time the empire attempts to exert influence over an otherwise independent kingdom they are swiftly reminded of how far they have fallen.

## The fall

The empire's decline was not swift. Unlike the fall of a king that ends with his beheading, the empire was subject to sieges, coups, assassinations, etc.. But, a plane spanning government posesses a momentum that lone rulers can only dream of. The empire fell to rubble not with a dramatic collapse, but with a whisper.

The fall started with the outer kingdoms. As the empire became more and more centralized, and its resources increasingly focused on defending its capitol the outer precincts began declaring independence. These declarations were rarely met with resistance, but they represented an existential threat to the empire. As rings of precincts broke off from the capital eventually the empire found themselves with little real power to stop the fall.

## The Capital

The Capital of the empire was built on the rubble of the mythical city of Ardensia. New Ardensia not only carried the Empire's seal, but also the divine responsibility to spread civilization. The soul of civilization's influence on the plane mirrors the rise and fall of the empire. Once one of the most influential gods who frequently chose avatars and influenced government, now Ardensia's influence is only felt in holy places and remnants of what once was. Today the city is largely abandoned. The descendants of the empire found their access to imported goods dwindling as their farm precincts deserted them, and without farmland on Ardensia they found themselves hungry. As the mining colonies left Ardensians found themselves recycling goods beyond their useful lifespan until their largest "craft" industry became scrapping. Eventually large swaths of the city were left to decline, and finally the capital of the empire was moved to Kalinkiev and the ruins of New Ardensia were left as the inheritance to those who remained behind. While Kalinkiev is officially the administrative hub of the empire it acts as little more than an island to host the various lords estates and summer homes.

## Legacy

While the legacy of the empire is felt throughout the plane, there are places where whole generations will live and die without ever learning that the empire ever existed. The most lasting influence of the empire is the many, many, many caches of arcanotech that were left in their wake. Warlords have rose to power armed with these weapons and have fell just as quickly when they stopped working. Finding these caches is almost as enriching as defeating a spring guardian, but there is a significant risk that someone beat you to it, or the empires wards remain in tact.

Beyond the artifacts left behind there are cells of the empire that still claim influence, but these lords are largely hanging on to an influence that has long since past.

## Edicts & Anathemas

Those who belong to the empire have a great variety of ethical codes. The edicts and anathemas of the individual largely align with the noble they serve.