---
title: The Hunting Grounds
---
# The Hunting Grounds

Once the site of the capitol city of Kaldaria, the hunting grounds are now home to overgrown wilderness and all sorts of monsters that emerged from the great chasm.

## A City so Grand

The capital of Kaldaria, of the same name, was an old city of brass and stone that fell to monsters after a great earthquake opened a great chasm and swallowed the eastern edge of the city. Through this gap swarmed thousands of deep dwellers who made quick work of the civilized folk. The militias of the city were able to contain the monsters to the South Central portion of the island, but little was able to be done to save the city.
Leaderless the towns of Kaldaria formed their own city states with a shared military responsible for containing the hordes of creatures that now inhabit the area known as the hunting grounds.

## Treasure and Honor

A modern pastime of adventurers who pay visit to Kaldaria is venturing across the patrol line into the infested woods to seek out treasure in the crumbling ruins, and challenge the pack alphas and warlords of the woods.

## Godwood of the Ruined Capital

Legend says that the Godwood without council of the hunting grounds grew from the site where the king was slain in the castle courtyard. Those who study such legends say that the blood of the ruler stained the ground of the courtyard and in anger Ardensia, the God of civilization, trapped the soul of the city within a tree so that someday, when the hunting grounds were reclaimed from the monsters, the city may be reborn from the rubble and retain its memory as a capitol of a unified nation.