---
title: "The Rancid Bogs of Hjelld"
---
# The Rancid Bogs of Hjelld

Once a prosperous wetland where wild rice was harvested by locals and all sorts of natural creatures frolicked the area now known as the Bogs of Hjelld are no place for living creatures. Created by dark magic the land has been poisoned and cursed. A fetid stink of rotting plant matter and animal flesh fills the air, and poisonous swamp gas bubbles from underneath the surface. While many hostile undead creatures wander this bog none is as fearsome as the Blighted Behemoth. This creature stands guardian over the corrupted spring that feeds the curse and quickly dispatches any adventurers foolish enough to venture into its domain.

## The Blighted Behemoth

Standing tens of feet tall this massive creature has unparalleled strength and dexterity. It moves through the bog with unmatched quickness and force. The Behemoth's arms are the width of tree trunks, and it's legs are twice that, blackened skin sloughs off of its body with every movement as new rancid flesh grows to take its place before meeting a similar fate. The creature stands on hind legs, but seems to amble through the swamp much like an orangutan. It's long arms launch the creature from stone outcroppings, to large dead trees, to unsuspecting prey. Its neck is nearly the same width as it's chest and it's face is nearly featureless aside from A large maw lined with needle teeth and a long nose that ends with a ring of short tentacles reminiscent of a star nosed mole. Those who have faced down the creature and lived say that your only means of escape is to land a solid blow on its facial tentacles and disorient the creature long enough to flee.