---
title: Jathera
---
# A Continent Spanning Nation

Among withering empires and city states Jathera, while only slightly larger than others by landmass, is a titan among mortals. Enriched by silver mines and a prospering steel industry, and empowered by harnessing the magic of several springs within its borders this nation brings an unparalleled ferocity to protecting its interests. Jathera has historically been a relatively insular nation, to the relief of nearby colonies, but has in the last decade or so been amassing a large navy.

# Aura of Protection

It is common for the wealthy and powerful to invest in protection; Be that in the form of magical auras, a particularly powerful magical artifact, body guards, or other such manner of protection. But, on the rare occasion that Jatherians are seen traveling the world, regardless of status or means they bear a mark more effective than any of the traditional wards. An individual bearing the official seal of the country is not shielded from physical harm, nor are they granted any enhanced strength. Most often the seal is a simple embroidered patch adorning otherwise unremarkable clothes. This seal carries with it the foreboding promise that should anything happen to the person wearing it the full force of the Jatherian military will bear down on the attacker. This promise is so well known that a Jatherian emissary can walk the fetid halls of an Ozothian tyrant's dungeon and emerge unscathed. This protection extends to any citizen wearing the official seal and as a result the Jatherian government extends the same swift and forceful punishment that it affords those foolish enough to threaten it's citizens to anyone who would dare create a forgery of its seal.

# Democratic and Fair

This nation was founded out of a union of mining towns oppressed by a now extinct monarchy that had worked them to the bone and took the profits of their citizens for their own to fund their lavish parties and decadent feasts. Led by a charismatic and practical former poet these miners rose against those who held the yoke about their neck and overthrew them in a series of increasingly bloody revolts. Once they seized the mines, the farms, ports and other centers of industry they simply starved the remaining aristocrats out of their gilded palaces. You may occasionally hear from aristocrats who fled the nation early in the revolution referring to the nation by its old name, Arakith, in derision. But know this, these individuals are only allowed to roam free without fear of being hunted down as a warning from Jatheria to those who would dare attempt to force them back into servitude.

Today the nation is governed in parliamentary fashion with no central leader. Notably, the political forces of their parliament are backed by different labor groups such as the mining and metalwork union, port and trade organization, and fieldworkers united among others.