---
title: Dulthrotha Plateau
---
# A Sea Above the Sea

The Dulthrotha Plateau is a strange landmass that rises thousands of feet above Mynara standard sea level. The Plateau is covered by water and surrounded by a ring of waterfalls as the water cascades over the edge of the plateau. Before you get the wrong idea, this is no mere mesa, The sea, while shallow by comparison, is deep enough to facilitate ship travel, ecosystems, and even holds several islands. The means by which the water collects on this surface is not entirely known, however what is known is that the water rushes up from deep holes in the sea floor and jets out creating dangerous currents. Caves on the islands that poke up from this sea are known to have deep miasma present at much shallower depths than elsewhere in the world likely due to the same pressures that cause the sea to flow forth from the ground.

# Travel to and from

Travel is complicated by the writhing currents, and vertical climb to get atop the plateau. A glideship is sufficient to leave the plateau, but to venture onto the plateau full airship capabilities are required. This causes the plateau to be largely isolated from the world at large and has shielded it from most of the chaos of the last hundred years post collapse of the imperium.