---
title: Black Winds
---
# Black Winds

The black winds is a marauding group of loosely associated pirates that populate the lawless regions of the ocean. The Black Winds moniker is more often used as a statement of intent than as an announcement of formal membership. The only guiding principles of the pirates who fly the Black Winds Flag is that they do not attack other ships flying the flag, and they do not draw the ire of organizations that would pose a threat to piracy. This "code", if you can call it that, is enforced by other pirates and if a pirate flying the flag is found to be in violation of these rules by their other seafaring counterparts it most frequently ends in a sunken ship.

Regional rules may be imposed by powerful pirate lords, but those rules are enforced by those individuals rather than by a centralized power. If the Black Winds pirates face an existential threat the most powerful of these pirates may establish a war council, however these informal governing bodies break apart as quickly as they are formed once the threat is dealt with.

## Retirement

The only way to leave a black winds crew is by taking a vow to never set sail again. If a former Black Winds affiliated crewman is discovered to have set foot on even a dingy they will be hunted down and killed. While not a hard rule, it is customary that if a former Black Winds pirate is brought to their former captain, alive or dead, a handsome bounty is to be paid out.

## Edicts

- Do not expose other members of the Black Winds to undue danger without their knowledge and consent
- Draw no more attention from powerful entities than is justified by the benefits of your venture
- Those who retire may never sail again

## Anathemas

- Endanger other Black Winds crews without their knowledge or consent
- Ally with 3rd parties against other Black Winds crews
- Lie about your affiliation to other Black Winds members