---
title: "The Dark Spire"
---
# The Dark Spire

Erupting from the sea the Watcher's tower looks over the waves. Rising above the jagged rocks that surround the tower the dark needle reaches towards the sky. Water flows from ports open in the outer walls and runs into the murky sea. Strange winged creatures fly about the tip of the spire striking at those who would attempt an approach by air. The tower seems to be constructed from a sort of black stone. Irregularly shaped blocks co-mingle to give the facade a jagged and rough appearance that gradually smooths the higher up you look. At night bright lights stream from nearly every crack or window in the massive structure and if you watch closely you can see large figures occasionally passing by the windows.

## The Watchers

The Watchers themselves have few confirmed sightings, but many afflicted with its curse report visions of a towering many armed figure cloaked in a billowing ragged garb with a single massive eye underneath a hood. It is typically described among shelves of books in a brightly lit library. What is certain about the creature is that it has constructed its lair around a Spring, and that those who approach its lair more often than not come away cursed by The Watchers to bear their mark.

Without first hand accounts it is difficult to say if there is a single creature that inhabits this tower, or if there are many of these entities tending their library. This is a matter of contentious debate for those few scholars who study the curse.

### The Watchers' curse

Those who bear The Watchers' mark are characterized by one or more bulbous eyes sprouting from their skin. Many cursed in this way cover the eye with a bandana when they leave the house, however many report that if they leave the covered with no predictability to it the eye will cause a searing pain until the covering is removed. Many believe that when The Watchers chooses to peer through these growths and finds them darkened he induces this pain to clear its vision.