---
title: "The Funnel"
---
# The Beginning
36 town folk including yourselves have journeyed up this mountainside along side the deputy ranger of Veridia Jurga Taff. Jurga is a gruff battle weary elf from where the ground stays frozen year round and your only chance of making it out of this journey alive. She has been tracking the beast for months; she's followed up on leads from survivors, tracked the creature's path from the wreckage of merchant carts, and so on. What she knows for certain is that this is no bear. This monster that has slain dozens of travelers and looted caravans covered its tracks, gathered valuables, and left behind things that weren't worth keeping. Many of the victims were killed, however the few survivors have reported kidnappings and a few have mentioned that it rambled at them in a language that they aren't familiar with. Whatever this thing is, it is stealthy, inhumanly quick, large, and needs to be stopped.
Given Jurga's research she has deduced that this cave is where the beast lives, and the corpses impaled on the stalagmites just inside its mouth. The stench of death wafts out from the dark hole in the mountain and causes your stomach to turn. Jurga groups you into squads of 4 and instructs you all to stick to the buddy system. 

::: {.callout-note}
## Jurga's Pep Talk

"Weapons out, eyes open, one of you carries a source of light at all times. You are not rangers, you are townsfolk who know how to hold a weapon. Stick close with me and you all might just make it out of here in one piece. Remember, don't be a hero. We strike together, we move together, and if someone gets separated from the group we do not go looking for them. everyone here has made this choice with the promise of glory and wealth at the end of this, but that is only a reward that those who survive will get a cut of. You all stand here for a moment while i go scout ahead and make sure that we aren't walking into an ambush then when i give you the signal you follow."
:::

As Jurga breaks from the group and walks into the cave you feel a sense of dread in the air. The gravity of this situation sets in. Just before you lose sight of Jurga in the inky dark of the cave you hear a loud crack before Jurga falls from view in a cloud of debris. She lets out a yell that is cut off by the sound of a body being run through. 
One of your fellow townsfolk runs ahead to investigate and shouts back "she fell in a spike pit. She's dead!" As they announce this several of your allies scatter, running away from the cave, some shake their heads and toss down their makeshift spears and pitch forks before tuning and leaving. Eventually it is only the 16 of you who remain.