---
title: "The Phantasm Forest"
---

# The Phantasm Forest

Deep beyond the groves of trees in the highlands of Hjelld the Phantasm Forest rests holding the secrets of travelers safe until such a time they are required by another. It is said that there is no better way to learn if your traveling companions are reliable than to rest underneath the canopy of pale yellow leaves of these shimmering trees. As travelers pass through the woods they witness visions of the lives and memories of previous travelers while leaving impressions of their own behind. These echoes of time may reveal truths of the realm, or guide adventurers to long forgotten treasures of ages past. However, the forest gives as much as it takes and those who venture into the forest must be without secret or shame unless they would leave these thoughts behind for others to view.
Over time as the memories of those who pass are concentrated within the leaves of these trees they are slowly transformed into parchment like sheets bearing tales of events long passed. The veins form lines of swirling text written in a language unique to the forest, and often adopted by those who study the arcane, that chronicle the memories contained within. These leaves are prized by mages and scholars for their magical properties and historical relevance respectively. One would think that these chronicles would be born of the recollection of a single individual, or jumbled inarticulate ramblings of several unrelated memories, however the forest seems to distribute the memories that are gathered in a sort of natural library. Before a leaf is released from the canopy the forest must be satisfied that a full telling of a story is captured, only then will the abscission of the leaf occur.
The wood seldom bothers with malicious or magnanimous action, however a way to guarantee that your memories never escape the forest is to prematurely harvest a leaf from the boughs of the greenwood. If a leaf is pulled from it's node before it's tale is captured the very earth will quake as The Warden excises your soul from your flesh.

## The Warden

Rising high through the canopies stands a magnificent gnarled tree weaved from the boughs of numerous intertwined aspen known as the Warden of the Phantasm Forest. This central Godwood's roots are the foundation that every tree in the wood grows from. The Warden stands in silent guardianship of the forest and will happily converse with travelers who seek guidance in good faith, but is equally eager to snuff the fire that burns within those who would do harm to the forest or interrupt their stories.
As well as guardian, The Warden serves the additional role as the collector of the completed stories. As the leaves fall from the Phantasm Forest's canopy they degrade and the knowledge is captured in the roots of The Warden. While the warden abhors the interruption of their stories, if a traveler gathers up fallen leaves and reads the text marked upon them The Warden is happy to move branches, uplift roots, and subtly manipulate the landscape to create a comfortable space to read. The bargain struck with The Warden in that moment that a leaf is gathered requires that once the reader has finished that the leaf be left behind among the underbrush of the forest.
Unlike many guardians who came upon a spring and became enthralled by the power that it offers there is no surface geyser that the magic imbued water erupts from in this forest. That's not to say that the shimmering pools of the forest aren't imbued with their own power, it is that these pools were not exposed until the roots of the forest drank from the aquifer below. While it is impossible to know for certain, it is believed that this magical forest first came about when the roots of The Warden, before it was known as The Warden of course, first pulled the magic from the earth to the surface.

## The Underbrush

Among the trees of this magnificent forest reside a variety of creatures that co-exist in this safe place. Many animals who live within the forest find themselves awakened and gifted a foundation of memories from a benevolent traveler to build their understanding around. In more exceptional cases plants that are not integrated into the Warden's root system find themselves similarly awakened. While not all awakened creatures are gifted with enlightened intellect those who know their language may find that even the lowliest of rodent has the capacity for more enlightened conversation. While The Warden is not all knowing within the bounds of it's forest it is through the friendship with it's denizens that it has eyes.
Also among the underbrush are specters that, contrary to common wisdom, are not true ghosts. The distinction between these ghostly entities and true incorporeal undead is that these renderings do not have their origins in the realm of spirits and rather the realm of memories and the mind. Because the forest is less concerns with the actions of individuals than it is with events and narratives these "spirits" are not absorbed into The Warden's collection. Particularly powerful memories of individuals can manifest as shimmering phantasms in their likeness as depicted by the memories of others. As you wander the grove you may find yourself face to face with heroes and leaders of nations, but not as they actually were rather finding them as how they were remembered.

## Phantasms

Once manifested these phantasms take agency over their experience and the older phantasms may evolve and become unrecognizable from the memories that bore them. One may come across a specter that began as a leader of a nation, but now holds the visage of a humble rabbit. Or perhaps meet the menacing beast that came from a spirit once known best for its amenability. It is best not to treat the specters as recordings of individuals long passed but rather as their own entity.

## Fruits of the forest

Those who wander may come across nourishing fruits of the forest. When presented with these gifts one is best to accept as the forest gives these gifts not only of fulfillment of body, but also of mind. Each berry, apple, or nettle is imbued with knowledge that The Warden has deemed you worthy of and when eaten will instantly grant you understanding. Occasionally these gifts contain the knowledge of how to approach the central clearing that The Warden inhabits So as to allow you a more extended audience with the forest. Without specific guidance from the forest even the most adept navigators will find themselves always on the edge of the warden's glade but never able to peer within.